services:
  qwen_vl:
    url: https://50067120bfc96748-8000.us-ca-6.gpu-instance.novita.ai
    rate_limit:
      calls: 10
      period: 1.0  # seconds
    max_concurrent: 20

  qwen_edit:
    url: http://192.168.0.238
    rate_limit:
      calls: 10
      period: 1.0
    max_concurrent: 20

  wan_i2v:
    url: http://192.168.0.238
    rate_limit:
      calls: 5
      period: 1.0
    max_concurrent: 10

  wan_talk:
    url: http://192.168.0.238
    rate_limit:
      calls: 5
      period: 1.0
    max_concurrent: 10

  video_concat:
    url: http://192.168.0.238
    rate_limit:
      calls: 5
      period: 1.0
    max_concurrent: 5
